---
all:
  hosts:
    local:
      ansible_host: localhost
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/env python3"
    worker_host:
      ansible_user: "linux"
      ansible_host: "{{ host_address }}"
      ansible_ssh_private_key_file: "{{ host_key }}"
