extra_parameters: |
    location / {
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
    }
    location / {
        proxy_pass         http://localhost:{{ web_server_port }};
        proxy_set_header   Host $host;
    }