---
- name: Checking running application
  hosts: worker_host
  become: yes
  tasks:
    - name: Get reporting processes list from remote host  # noqa 301 305
      ignore_errors: yes
      shell: "ps aux | grep 'alertawebaddon' | awk '{print $2}'"
      register: process_monitor
    - name: Kill running reporting processes  # noqa 301 305
      ignore_errors: yes
      shell: "kill {{ process_monitor.stdout_lines[0] }}"
    - name: Waiting for status
      wait_for:
        path: "/proc/{{ process_monitor.stdout_lines[0] }}/status"
        state: absent
      ignore_errors: yes

- name: Install and run server
  hosts: worker_host
  become: yes
  environment:
    GITHUB_OAUTH_CLIENT_SECRET: "{{ lookup('env', 'GITHUB_OAUTH_CLIENT_SECRET') }}"
    GITHUB_OAUTH_CLIENT_ID: "{{ lookup('env', 'GITHUB_OAUTH_CLIENT_ID') }}"
    APP_SECRET_KEY: "{{ lookup('env', 'APP_SECRET_KEY') }}"
    DATABASE_URL: "{{ lookup('env', 'DATABASE_URL') }}"
    GITHUB_OAUTH_ALLOWED_ORGANIZATIONS: "{{ lookup('env', 'GITHUB_OAUTH_ALLOWED_ORGANIZATIONS') }}"
    OAUTHLIB_INSECURE_TRANSPORT: true
    PROXY_PREFIX_PATH: "{{ lookup('env', 'PROXY_PREFIX_PATH') }}"
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install required packages
      apt:
        state: present
        name: "{{ item }}"
      with_items:
          - python3-setuptools
          - python3-pip
          - python3-dev
          - python3-venv
          - cron

    - name: Checkout from git
      git:
        repo: 'https://github.com/opentelekomcloud-infra/alerta-web-addon'
        dest: "{{ base_path }}"
        force: yes
        depth: 1
        version: HEAD

    - name: Create venv
      pip:
        name: pip
        virtualenv: "{{ virtualenv_path }}"
        virtualenv_command: '/usr/bin/python3 -m venv'

    - name: install Python requirements
      pip:
        requirements: "{{ base_path }}/playbooks/files/requirements.txt"
        virtualenv: "{{ virtualenv_path }}"

    - name: Start server  # noqa 301 305
      shell: "nohup {{ virtualenv_path }}/bin/python -m alertawebaddon --port {{ web_server_port }} &"
      args:
        chdir: "{{ base_path }}"

- name: Install and setup nginx
  hosts: worker_host
  become: yes
  vars_files:
  - "./vars/nginx_parameters.yml"
  vars:
    certbot_admin_email: "webaddon@{{ domain }}"
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services: []
    certbot_auto_renew_user: linux
    certbot_auto_renew_minute: "20"
    certbot_auto_renew_hour: "5"
    certbot_certs:
      - domains:
          - "{{ domain }}"
    nginx_remove_default_vhost: yes
    nginx_vhosts:
    - listen: "443 ssl"
      server_name: "{{ domain }}"
      extra_parameters: "{{ extra_parameters }}"
  roles:
    - role: geerlingguy.certbot
      when: skip_nginx|bool == false
    - role: geerlingguy.nginx
      when: skip_nginx|bool == false
