---
- name: Install role from Ansible Galaxy
  hosts: worker_host
  become: yes
  tasks:
    - name: install nginx role
      shell: "ansible-galaxy install geerlingguy.nginx"

- name: Install and setup nginx
  hosts: worker_host
  become: yes
  vars_files:
  - "./vars/nginx_parameters.yml"
  roles:
  - role: geerlingguy.nginx
    vars:
      nginx_remove_default_vhost: yes
      nginx_vhosts:
      - listen: "80"
        server_name: "localhost"
        extra_parameters: "{{ extra_parameters }}"