---
- name: Install role from Ansible Galaxy
  hosts: worker_host
  become: yes
  tasks:
    - name: install nginx role
      shell: "ansible-galaxy install geerlingguy.nginx"

- name: Install and run server
  hosts: worker_host
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Create directory for virtual environment
      file:
        path: "{{ virtualenv_path }}"
        state: directory
        mode: "0755"

    - name: Install required packages
      apt:
        name:
          - python3-setuptools
          - python3-pip
          - build-essential
          - python3-dev
          - python3-venv

    - name: Create venv
      pip:
        name: pip
        virtualenv: "{{ virtualenv_path }}"
        virtualenv_command: '/usr/bin/python3 -m venv'

    - name: Install poetry into venv
      pip:
        name: poetry
        virtualenv: "{{ virtualenv_path }}"

    - name: Checkout from git
      git:
        repo: 'https://github.com/opentelekomcloud-infra/alerta-web-addon'
        dest: "{{ base_path }}"
        force: yes
        depth: 1

    - name: install Python requirements with Poetry
      shell: "{{ virtualenv_path }}/bin/python poetry install"
      args:
        chdir: "{{ base_path }}"

    - name: Start server
      shell: "start-stop-daemon -Sbmvp /tmp/server.pid -x {{ virtualenv_path }}/bin/python {{ base_path }}/server.py --dbstring {{ dbstring }} --port {{ web_server_port }}" # noqa 301 305

- name: Install and setup nginx
  hosts: worker_host
  become: yes
  vars_files:
  - "./vars/nginx_parameters.yml"
  roles:
  - role: geerlingguy.nginx
    vars:
      nginx_remove_default_vhost: yes
      nginx_vhosts:
      - listen: "80"
        server_name: "localhost"
        extra_parameters: "{{ extra_parameters }}"