---
- name: Install and run server
  hosts: worker_host
  become: yes
  environment:
    GITHUB_OAUTH_CLIENT_SECRET: "{{ lookup('env', 'GITHUB_OAUTH_CLIENT_SECRET') }}"
    GITHUB_OAUTH_CLIENT_ID: "{{ lookup('env', 'GITHUB_OAUTH_CLIENT_ID') }}"
    APP_SECRET_KEY: "{{ lookup('env', 'APP_SECRET_KEY') }}"
    DATABASE_URL: "{{ lookup('env', 'DATABASE_URL') }}"
    OAUTHLIB_INSECURE_TRANSPORT: true
  tasks:

    - name: Install required packages
      package:
        state: present
        name: "{{ item }}"
      with_items:
          - python3-setuptools
          - python3-pip
          - python3-devel

    - name: Checkout from git
      git:
        repo: 'https://github.com/opentelekomcloud-infra/alerta-web-addon'
        dest: "{{ base_path }}"
        force: yes
        depth: 1
        version: oauth

    - name: Create venv
      pip:
        name: pip
        virtualenv: "{{ virtualenv_path }}"
        virtualenv_command: '/usr/bin/python3 -m venv'

    - name: install Python requirements
      pip:
        requirements: "{{ base_path }}/playbooks/files/requirements.txt"
        virtualenv: "{{ virtualenv_path }}"

    - name: Start server  # noqa 301 305
      shell: "nohup {{ virtualenv_path }}/bin/python -m alertawebaddon --port {{ web_server_port }} &"
      args:
        chdir: "{{ base_path }}"

- name: Install and setup nginx
  hosts: worker_host
  become: yes
  vars_files:
  - "./vars/nginx_parameters.yml"
  roles:
  - role: geerlingguy.nginx
    vars:
      nginx_remove_default_vhost: yes
      nginx_vhosts:
      - listen: "80"
        server_name: "localhost"
        extra_parameters: "{{ extra_parameters }}"
    when: skip_nginx|bool == false
